import {
  ArrowDownRight,
  ArrowRightLeft,
  ArrowUpRight,
  Banknote,
  Bus,
  Calendar,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDashed,
  Clapperboard,
  CreditCard,
  Download,
  Equal,
  Flame,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Info,
  Landmark,
  Laptop,
  LayoutDashboard,
  List,
  Moon,
  Pencil,
  PiggyBank,
  Plus,
  Repeat,
  RotateCcw,
  Search,
  Settings,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Sun,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Upload,
  Utensils,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icons are referenced by kebab-case name from domain data (categories, insights),
 * so `lib/` never imports React. Only what is listed here ships in the bundle.
 */
const REGISTRY: Record<string, LucideIcon> = {
  'alert-triangle': TriangleAlert,
  'arrow-down-right': ArrowDownRight,
  'arrow-right-left': ArrowRightLeft,
  'arrow-up-right': ArrowUpRight,
  banknote: Banknote,
  bus: Bus,
  calendar: Calendar,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-dashed': CircleDashed,
  clapperboard: Clapperboard,
  'credit-card': CreditCard,
  download: Download,
  equal: Equal,
  flame: Flame,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  home: House,
  info: Info,
  landmark: Landmark,
  laptop: Laptop,
  'layout-dashboard': LayoutDashboard,
  list: List,
  moon: Moon,
  pencil: Pencil,
  'pie-chart': ChartPie,
  'piggy-bank': PiggyBank,
  plus: Plus,
  repeat: Repeat,
  reset: RotateCcw,
  search: Search,
  settings: Settings,
  'shopping-bag': ShoppingBag,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sun: Sun,
  target: Target,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  upload: Upload,
  utensils: Utensils,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 16, className, strokeWidth = 1.75 }: IconProps) {
  const Cmp = REGISTRY[name] ?? CircleDashed;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}
